---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: registrar_devolucion-svc
  name: registrar_devolucion-svc
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: registrar_devolucion-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: registrar_devolucion-svc
    spec:
      containers:
      - name: registrar_devolucion-svc
        image: docker.io/usuario/registrar_devolucion
        imagePullPolicy: IfNotPresent
        env:
          - name: API_QUEUE
            value: "RABBIT_IP"
        ports:
        - containerPort: 3010
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: registrar_devolucion-svc
  name: registrar_devolucion-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3010
  selector:
    run: registrar_devolucion-svc
  sessionAffinity: None
  type: LoadBalancer